### PR TITLE
prevent let-floating trick tweak: swap `const m r` for `seq r m`

### LINKED ISSUE #149: Tests fail with profiling enabled
See the following output:

```
# ollie at nixos-desktop in ~/work/reactive-banana/reactive-banana on git:master ✖︎ [16:28:02]
→ cabal clean                                                                  ~/work/reactive-banana/reactive-banana
cleaning...

# ollie at nixos-desktop in ~/work/reactive-banana/reactive-banana on git:master ✖︎ [16:28:14]
→ nix-shell --run 'cabal test'                                                 ~/work/reactive-banana/reactive-banana
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Warning: The package list for 'hackage.haskell.org' is 80 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Configuring reactive-banana-1.1.0.1...
Preprocessing library reactive-banana-1.1.0.1...
[ 1 of 22] Compiling Reactive.Banana.Prim.Util ( src/Reactive/Banana/Prim/Util.hs, dist/build/Reactive/Banana/Prim/Util.o )
[ 2 of 22] Compiling Reactive.Banana.Prim.OrderedBag ( src/Reactive/Banana/Prim/OrderedBag.hs, dist/build/Reactive/Banana/Prim/OrderedBag.o )
[ 3 of 22] Compiling Reactive.Banana.Prim.Graph ( src/Reactive/Banana/Prim/Graph.hs, dist/build/Reactive/Banana/Prim/Graph.o )
[ 4 of 22] Compiling Reactive.Banana.Prim.Cached ( src/Reactive/Banana/Prim/Cached.hs, dist/build/Reactive/Banana/Prim/Cached.o )
[ 5 of 22] Compiling Reactive.Banana.Model ( src/Reactive/Banana/Model.hs, dist/build/Reactive/Banana/Model.o )
[ 6 of 22] Compiling Control.Monad.Trans.ReaderWriterIO ( src/Control/Monad/Trans/ReaderWriterIO.hs, dist/build/Control/Monad/Trans/ReaderWriterIO.o )
[ 7 of 22] Compiling Control.Monad.Trans.RWSIO ( src/Control/Monad/Trans/RWSIO.hs, dist/build/Control/Monad/Trans/RWSIO.o )
[ 8 of 22] Compiling Reactive.Banana.Prim.Types ( src/Reactive/Banana/Prim/Types.hs, dist/build/Reactive/Banana/Prim/Types.o )
[ 9 of 22] Compiling Reactive.Banana.Prim.Dependencies ( src/Reactive/Banana/Prim/Dependencies.hs, dist/build/Reactive/Banana/Prim/Dependencies.o )
[10 of 22] Compiling Reactive.Banana.Prim.Plumbing ( src/Reactive/Banana/Prim/Plumbing.hs, dist/build/Reactive/Banana/Prim/Plumbing.o )
[11 of 22] Compiling Reactive.Banana.Prim.Combinators ( src/Reactive/Banana/Prim/Combinators.hs, dist/build/Reactive/Banana/Prim/Combinators.o )
[12 of 22] Compiling Reactive.Banana.Prim.Evaluation ( src/Reactive/Banana/Prim/Evaluation.hs, dist/build/Reactive/Banana/Prim/Evaluation.o )
[13 of 22] Compiling Reactive.Banana.Prim.IO ( src/Reactive/Banana/Prim/IO.hs, dist/build/Reactive/Banana/Prim/IO.o )
[14 of 22] Compiling Reactive.Banana.Prim.Compile ( src/Reactive/Banana/Prim/Compile.hs, dist/build/Reactive/Banana/Prim/Compile.o )
[15 of 22] Compiling Reactive.Banana.Prim ( src/Reactive/Banana/Prim.hs, dist/build/Reactive/Banana/Prim.o )
[16 of 22] Compiling Reactive.Banana.Prim.Test ( src/Reactive/Banana/Prim/Test.hs, dist/build/Reactive/Banana/Prim/Test.o )
[17 of 22] Compiling Control.Event.Handler ( src/Control/Event/Handler.hs, dist/build/Control/Event/Handler.o )
[18 of 22] Compiling Reactive.Banana.Internal.Combinators ( src/Reactive/Banana/Internal/Combinators.hs, dist/build/Reactive/Banana/Internal/Combinators.o )
[19 of 22] Compiling Reactive.Banana.Types ( src/Reactive/Banana/Types.hs, dist/build/Reactive/Banana/Types.o )
[20 of 22] Compiling Reactive.Banana.Combinators ( src/Reactive/Banana/Combinators.hs, dist/build/Reactive/Banana/Combinators.o )
[21 of 22] Compiling Reactive.Banana.Frameworks ( src/Reactive/Banana/Frameworks.hs, dist/build/Reactive/Banana/Frameworks.o )
[22 of 22] Compiling Reactive.Banana  ( src/Reactive/Banana.hs, dist/build/Reactive/Banana.o )
Preprocessing test suite 'tests' for reactive-banana-1.1.0.1...
[ 1 of 19] Compiling Reactive.Banana.Prim.Util ( src/Reactive/Banana/Prim/Util.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Util.o )
[ 2 of 19] Compiling Reactive.Banana.Prim.OrderedBag ( src/Reactive/Banana/Prim/OrderedBag.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/OrderedBag.o )
[ 3 of 19] Compiling Reactive.Banana.Prim.Graph ( src/Reactive/Banana/Prim/Graph.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Graph.o )
[ 4 of 19] Compiling Reactive.Banana.Prim.Cached ( src/Reactive/Banana/Prim/Cached.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Cached.o )
[ 5 of 19] Compiling Reactive.Banana.Model ( src/Reactive/Banana/Model.hs, dist/build/tests/tests-tmp/Reactive/Banana/Model.o )
[ 6 of 19] Compiling Control.Monad.Trans.ReaderWriterIO ( src/Control/Monad/Trans/ReaderWriterIO.hs, dist/build/tests/tests-tmp/Control/Monad/Trans/ReaderWriterIO.o )
[ 7 of 19] Compiling Control.Monad.Trans.RWSIO ( src/Control/Monad/Trans/RWSIO.hs, dist/build/tests/tests-tmp/Control/Monad/Trans/RWSIO.o )
[ 8 of 19] Compiling Reactive.Banana.Prim.Types ( src/Reactive/Banana/Prim/Types.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Types.o )
[ 9 of 19] Compiling Reactive.Banana.Prim.Dependencies ( src/Reactive/Banana/Prim/Dependencies.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Dependencies.o )
[10 of 19] Compiling Reactive.Banana.Prim.Plumbing ( src/Reactive/Banana/Prim/Plumbing.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Plumbing.o )
[11 of 19] Compiling Reactive.Banana.Prim.Combinators ( src/Reactive/Banana/Prim/Combinators.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Combinators.o )
[12 of 19] Compiling Reactive.Banana.Prim.Evaluation ( src/Reactive/Banana/Prim/Evaluation.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Evaluation.o )
[13 of 19] Compiling Reactive.Banana.Prim.IO ( src/Reactive/Banana/Prim/IO.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/IO.o )
[14 of 19] Compiling Reactive.Banana.Prim.Compile ( src/Reactive/Banana/Prim/Compile.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Compile.o )
[15 of 19] Compiling Reactive.Banana.Prim ( src/Reactive/Banana/Prim.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim.o )
[16 of 19] Compiling Control.Event.Handler ( src/Control/Event/Handler.hs, dist/build/tests/tests-tmp/Control/Event/Handler.o )
[17 of 19] Compiling Reactive.Banana.Internal.Combinators ( src/Reactive/Banana/Internal/Combinators.hs, dist/build/tests/tests-tmp/Reactive/Banana/Internal/Combinators.o )
[18 of 19] Compiling Reactive.Banana.Test.Plumbing ( src/Reactive/Banana/Test/Plumbing.hs, dist/build/tests/tests-tmp/Reactive/Banana/Test/Plumbing.o )
[19 of 19] Compiling Main             ( src/Reactive/Banana/Test.hs, dist/build/tests/tests-tmp/Main.o )
Linking dist/build/tests/tests ...
Running 1 test suites...
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to: dist/test/reactive-banana-1.1.0.1-tests.log
1 of 1 test suites (1 of 1 test cases) passed.

# ollie at nixos-desktop in ~/work/reactive-banana/reactive-banana on git:master ✖︎ [16:28:33]
→ nix-shell --run 'cabal clean'                                                ~/work/reactive-banana/reactive-banana
cleaning...

# ollie at nixos-desktop in ~/work/reactive-banana/reactive-banana on git:master ✖︎ [16:29:03]
→ nix-shell --run 'cabal configure --enable-profiling --enable-tests'          ~/work/reactive-banana/reactive-banana
Warning: The package list for 'hackage.haskell.org' is 80 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Configuring reactive-banana-1.1.0.1...

# ollie at nixos-desktop in ~/work/reactive-banana/reactive-banana on git:master ✖︎ [16:29:11]
→ cabal test                                                                   ~/work/reactive-banana/reactive-banana
Preprocessing library reactive-banana-1.1.0.1...
[ 1 of 22] Compiling Reactive.Banana.Prim.Util ( src/Reactive/Banana/Prim/Util.hs, dist/build/Reactive/Banana/Prim/Util.o )
[ 2 of 22] Compiling Reactive.Banana.Prim.OrderedBag ( src/Reactive/Banana/Prim/OrderedBag.hs, dist/build/Reactive/Banana/Prim/OrderedBag.o )
[ 3 of 22] Compiling Reactive.Banana.Prim.Graph ( src/Reactive/Banana/Prim/Graph.hs, dist/build/Reactive/Banana/Prim/Graph.o )
[ 4 of 22] Compiling Reactive.Banana.Prim.Cached ( src/Reactive/Banana/Prim/Cached.hs, dist/build/Reactive/Banana/Prim/Cached.o )
[ 5 of 22] Compiling Reactive.Banana.Model ( src/Reactive/Banana/Model.hs, dist/build/Reactive/Banana/Model.o )
[ 6 of 22] Compiling Control.Monad.Trans.ReaderWriterIO ( src/Control/Monad/Trans/ReaderWriterIO.hs, dist/build/Control/Monad/Trans/ReaderWriterIO.o )
[ 7 of 22] Compiling Control.Monad.Trans.RWSIO ( src/Control/Monad/Trans/RWSIO.hs, dist/build/Control/Monad/Trans/RWSIO.o )
[ 8 of 22] Compiling Reactive.Banana.Prim.Types ( src/Reactive/Banana/Prim/Types.hs, dist/build/Reactive/Banana/Prim/Types.o )
[ 9 of 22] Compiling Reactive.Banana.Prim.Dependencies ( src/Reactive/Banana/Prim/Dependencies.hs, dist/build/Reactive/Banana/Prim/Dependencies.o )
[10 of 22] Compiling Reactive.Banana.Prim.Plumbing ( src/Reactive/Banana/Prim/Plumbing.hs, dist/build/Reactive/Banana/Prim/Plumbing.o )
[11 of 22] Compiling Reactive.Banana.Prim.Combinators ( src/Reactive/Banana/Prim/Combinators.hs, dist/build/Reactive/Banana/Prim/Combinators.o )
[12 of 22] Compiling Reactive.Banana.Prim.Evaluation ( src/Reactive/Banana/Prim/Evaluation.hs, dist/build/Reactive/Banana/Prim/Evaluation.o )
[13 of 22] Compiling Reactive.Banana.Prim.IO ( src/Reactive/Banana/Prim/IO.hs, dist/build/Reactive/Banana/Prim/IO.o )
[14 of 22] Compiling Reactive.Banana.Prim.Compile ( src/Reactive/Banana/Prim/Compile.hs, dist/build/Reactive/Banana/Prim/Compile.o )
[15 of 22] Compiling Reactive.Banana.Prim ( src/Reactive/Banana/Prim.hs, dist/build/Reactive/Banana/Prim.o )
[16 of 22] Compiling Reactive.Banana.Prim.Test ( src/Reactive/Banana/Prim/Test.hs, dist/build/Reactive/Banana/Prim/Test.o )
[17 of 22] Compiling Control.Event.Handler ( src/Control/Event/Handler.hs, dist/build/Control/Event/Handler.o )
[18 of 22] Compiling Reactive.Banana.Internal.Combinators ( src/Reactive/Banana/Internal/Combinators.hs, dist/build/Reactive/Banana/Internal/Combinators.o )
[19 of 22] Compiling Reactive.Banana.Types ( src/Reactive/Banana/Types.hs, dist/build/Reactive/Banana/Types.o )
[20 of 22] Compiling Reactive.Banana.Combinators ( src/Reactive/Banana/Combinators.hs, dist/build/Reactive/Banana/Combinators.o )
[21 of 22] Compiling Reactive.Banana.Frameworks ( src/Reactive/Banana/Frameworks.hs, dist/build/Reactive/Banana/Frameworks.o )
[22 of 22] Compiling Reactive.Banana  ( src/Reactive/Banana.hs, dist/build/Reactive/Banana.o )
[ 1 of 22] Compiling Reactive.Banana.Prim.Util ( src/Reactive/Banana/Prim/Util.hs, dist/build/Reactive/Banana/Prim/Util.p_o )
[ 2 of 22] Compiling Reactive.Banana.Prim.OrderedBag ( src/Reactive/Banana/Prim/OrderedBag.hs, dist/build/Reactive/Banana/Prim/OrderedBag.p_o )
[ 3 of 22] Compiling Reactive.Banana.Prim.Graph ( src/Reactive/Banana/Prim/Graph.hs, dist/build/Reactive/Banana/Prim/Graph.p_o )
[ 4 of 22] Compiling Reactive.Banana.Prim.Cached ( src/Reactive/Banana/Prim/Cached.hs, dist/build/Reactive/Banana/Prim/Cached.p_o )
[ 5 of 22] Compiling Reactive.Banana.Model ( src/Reactive/Banana/Model.hs, dist/build/Reactive/Banana/Model.p_o )
[ 6 of 22] Compiling Control.Monad.Trans.ReaderWriterIO ( src/Control/Monad/Trans/ReaderWriterIO.hs, dist/build/Control/Monad/Trans/ReaderWriterIO.p_o )
[ 7 of 22] Compiling Control.Monad.Trans.RWSIO ( src/Control/Monad/Trans/RWSIO.hs, dist/build/Control/Monad/Trans/RWSIO.p_o )
[ 8 of 22] Compiling Reactive.Banana.Prim.Types ( src/Reactive/Banana/Prim/Types.hs, dist/build/Reactive/Banana/Prim/Types.p_o )
[ 9 of 22] Compiling Reactive.Banana.Prim.Dependencies ( src/Reactive/Banana/Prim/Dependencies.hs, dist/build/Reactive/Banana/Prim/Dependencies.p_o )
[10 of 22] Compiling Reactive.Banana.Prim.Plumbing ( src/Reactive/Banana/Prim/Plumbing.hs, dist/build/Reactive/Banana/Prim/Plumbing.p_o )
[11 of 22] Compiling Reactive.Banana.Prim.Combinators ( src/Reactive/Banana/Prim/Combinators.hs, dist/build/Reactive/Banana/Prim/Combinators.p_o )
[12 of 22] Compiling Reactive.Banana.Prim.Evaluation ( src/Reactive/Banana/Prim/Evaluation.hs, dist/build/Reactive/Banana/Prim/Evaluation.p_o )
[13 of 22] Compiling Reactive.Banana.Prim.IO ( src/Reactive/Banana/Prim/IO.hs, dist/build/Reactive/Banana/Prim/IO.p_o )
[14 of 22] Compiling Reactive.Banana.Prim.Compile ( src/Reactive/Banana/Prim/Compile.hs, dist/build/Reactive/Banana/Prim/Compile.p_o )
[15 of 22] Compiling Reactive.Banana.Prim ( src/Reactive/Banana/Prim.hs, dist/build/Reactive/Banana/Prim.p_o )
[16 of 22] Compiling Reactive.Banana.Prim.Test ( src/Reactive/Banana/Prim/Test.hs, dist/build/Reactive/Banana/Prim/Test.p_o )
[17 of 22] Compiling Control.Event.Handler ( src/Control/Event/Handler.hs, dist/build/Control/Event/Handler.p_o )
[18 of 22] Compiling Reactive.Banana.Internal.Combinators ( src/Reactive/Banana/Internal/Combinators.hs, dist/build/Reactive/Banana/Internal/Combinators.p_o )
[19 of 22] Compiling Reactive.Banana.Types ( src/Reactive/Banana/Types.hs, dist/build/Reactive/Banana/Types.p_o )
[20 of 22] Compiling Reactive.Banana.Combinators ( src/Reactive/Banana/Combinators.hs, dist/build/Reactive/Banana/Combinators.p_o )
[21 of 22] Compiling Reactive.Banana.Frameworks ( src/Reactive/Banana/Frameworks.hs, dist/build/Reactive/Banana/Frameworks.p_o )
[22 of 22] Compiling Reactive.Banana  ( src/Reactive/Banana.hs, dist/build/Reactive/Banana.p_o )
Preprocessing test suite 'tests' for reactive-banana-1.1.0.1...
[ 1 of 19] Compiling Reactive.Banana.Prim.Util ( src/Reactive/Banana/Prim/Util.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Util.p_o )
[ 2 of 19] Compiling Reactive.Banana.Prim.OrderedBag ( src/Reactive/Banana/Prim/OrderedBag.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/OrderedBag.p_o )
[ 3 of 19] Compiling Reactive.Banana.Prim.Graph ( src/Reactive/Banana/Prim/Graph.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Graph.p_o )
[ 4 of 19] Compiling Reactive.Banana.Prim.Cached ( src/Reactive/Banana/Prim/Cached.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Cached.p_o )
[ 5 of 19] Compiling Reactive.Banana.Model ( src/Reactive/Banana/Model.hs, dist/build/tests/tests-tmp/Reactive/Banana/Model.p_o )
[ 6 of 19] Compiling Control.Monad.Trans.ReaderWriterIO ( src/Control/Monad/Trans/ReaderWriterIO.hs, dist/build/tests/tests-tmp/Control/Monad/Trans/ReaderWriterIO.p_o )
[ 7 of 19] Compiling Control.Monad.Trans.RWSIO ( src/Control/Monad/Trans/RWSIO.hs, dist/build/tests/tests-tmp/Control/Monad/Trans/RWSIO.p_o )
[ 8 of 19] Compiling Reactive.Banana.Prim.Types ( src/Reactive/Banana/Prim/Types.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Types.p_o )
[ 9 of 19] Compiling Reactive.Banana.Prim.Dependencies ( src/Reactive/Banana/Prim/Dependencies.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Dependencies.p_o )
[10 of 19] Compiling Reactive.Banana.Prim.Plumbing ( src/Reactive/Banana/Prim/Plumbing.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Plumbing.p_o )
[11 of 19] Compiling Reactive.Banana.Prim.Combinators ( src/Reactive/Banana/Prim/Combinators.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Combinators.p_o )
[12 of 19] Compiling Reactive.Banana.Prim.Evaluation ( src/Reactive/Banana/Prim/Evaluation.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Evaluation.p_o )
[13 of 19] Compiling Reactive.Banana.Prim.IO ( src/Reactive/Banana/Prim/IO.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/IO.p_o )
[14 of 19] Compiling Reactive.Banana.Prim.Compile ( src/Reactive/Banana/Prim/Compile.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim/Compile.p_o )
[15 of 19] Compiling Reactive.Banana.Prim ( src/Reactive/Banana/Prim.hs, dist/build/tests/tests-tmp/Reactive/Banana/Prim.p_o )
[16 of 19] Compiling Control.Event.Handler ( src/Control/Event/Handler.hs, dist/build/tests/tests-tmp/Control/Event/Handler.p_o )
[17 of 19] Compiling Reactive.Banana.Internal.Combinators ( src/Reactive/Banana/Internal/Combinators.hs, dist/build/tests/tests-tmp/Reactive/Banana/Internal/Combinators.p_o )
[18 of 19] Compiling Reactive.Banana.Test.Plumbing ( src/Reactive/Banana/Test/Plumbing.hs, dist/build/tests/tests-tmp/Reactive/Banana/Test/Plumbing.p_o )
[19 of 19] Compiling Main             ( src/Reactive/Banana/Test.hs, dist/build/tests/tests-tmp/Main.p_o )
Linking dist/build/tests/tests ...
Running 1 test suites...
Test suite tests: RUNNING...
Simple:
  id: [OK]
  never1: [OK]
  fmap1: [OK]
  filter1: [OK]
  filter2: [OK]
  accumE1: [OK]
Complex:
  counter: [OK]
  double: [OK]
  sharing: [OK]
  unionFilter: [OK]
  recursive1A: [OK]
  recursive1B: [OK]
  recursive2: [OK]
  recursive3: [OK]
  recursive4a: [OK]
  accumBvsE: [OK]
Dynamic Event Switching:
  observeE_id: [OK]
[Just 0,Just 0,Just 0,Just 0,Just 0,Just 0,Just 0,Just 0]
[Just 0,Just 0,Just 2,Just 3,Just 4,Just 5,Just 6,Just 7]
  observeE_stepper: [Failed]

  valueB_immediate: [OK]
  dynamic_apply: [OK]
  switchE1: [OK]
  switchB1: [OK]
  switchB2: [OK]
Regression tests:
  issue79: [OK]

         Test Cases   Total       
 Passed  23           23          
 Failed  1            1           
 Total   24           24          
Test suite tests: FAIL
Test suite logged to: dist/test/reactive-banana-1.1.0.1-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
```

### PR DESCRIPTION
**Pull request by mitchellwrosen**
as suggested by @HeinrichApfelmus in #149. this variant seems to work better under ghc -prof

fixes #149

### CODE REVIEW

File: reactive-banana/src/Reactive/Banana/Prim/High/Combinators.hs [hunk 1]
```diff
@@ -34,8 +34,15 @@ liftBuild = lift
...
 interpret :: (Event a -> Moment (Event b)) -> [Maybe a] -> IO [Maybe b]
-interpret f = Prim.interpret $ \pulse -> runReaderT (g pulse) undefined
-    where
+interpret f xs = do
+    -- This event network is unused, but it can't be undefined due to the seq in cacheAndSchedule
+    eventNetwork <- do
+      actuated <- newIORef False
+      size <- newIORef 0
+      s <- newMVar =<< Prim.emptyNetwork
+      pure EventNetwork{ actuated, size, s }
```
Comment (HeinrichApfelmus) [inline reactive-banana/src/Reactive/Banana/Prim/High/Combinators.hs:43]:
```suggestion
    eventNetwork <- compile $ pure ()
```

I would like to re-use a top-level definition here. 🤔

**Review by HeinrichApfelmus — APPROVED** [review]
Thanks! 😊 Feel free to merge after addressing comment.

File: reactive-banana/src/Reactive/Banana/Prim/High/Combinators.hs (hunk 1 above)
Comment (mitchellwrosen) [reply reactive-banana/src/Reactive/Banana/Prim/High/Combinators.hs:43]: Oh, that's better 🙈
